### ISSUE TITLE
Fundraising Project Template

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/knowledgebase-content#100]
### Overview
Create a template to collect information about projects for fundraising purposes.

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
- [ ] Each project needs to answer the following questions
- [x] Brief explanation of what the project is
- [x] Who is going to benefit 
- [x] Why it is needed in the community
- [ ] Provide data to back up why its necessary and so it can be measured  
- [ ] We want to be able to show the returns and gains

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.

**Comment by ExperimentsInHonesty** [comment]
@Aditya23soni I copied the document from the Expunge Assist drive to the folder [knowlegbase-content >  By Title > 0100 [DRAFT] Fundraising Project Template](https://drive.google.com/drive/folders/136Wz8w_r2SsHfK6cTrUaKs1j3V1LB-mN)

![image](https://github.com/user-attachments/assets/e31af605-f68d-4e4a-abdc-b615a4f98f15)

**Comment by ExperimentsInHonesty** [comment]
@Aditya23soni Please see what I changed the top of the document too

### Before
<img src="https://github.com/user-attachments/assets/ee5bde1f-341d-416b-81b8-718f8813bbe6" width=300px>


### After
<img src="https://github.com/user-attachments/assets/b2d6e5a3-15c7-4836-8661-2435d023abcd" width=300px>
