### ISSUE TITLE
Create a Guide/Template : How to Add Resumes Bullets to your Issue

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/knowledgebase-content#101]
### Overview
We need to create a guide to making issues that communicate experience gained so it will be easier for people to add work to their resume.  (i.e, if we pre-write the bullet, then it can just be added to the person's resume when they finish the work).

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions
- Google Drive Folder for this Guide’s documents and shortcuts (to documents in other locations) [0101 [DRAFT] How to Add Resumes Bullets to your Issue ](https://drive.google.com/drive/folders/1fjzpBF2a8oUX_0cqDsvCEGcXsBw-ZEfA)
- Example issue from HackforLA team https://github.com/hackforla/website/issues/511

#### Add a special note into the guide:
This is for when your project board is at an excellent level; meaning don't attempt this if you are having trouble just keeping the board organized.

#### Potential Applications
- [ ] Make a list of resume bullet points categorized into roles
- [ ] Edit the standard template to include a link to this list and a space to put the relevant resume bullet point for the issue

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.

**Comment by fchan218** [comment]
@Aditya23soni please change the statuses on both the project boards to "needs to be triaged"

**Comment by AkhilaA12** [comment]
Shortcuts are now added.
