### ISSUE TITLE
Create a Template: List of product management - project inventory items

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/knowledgebase-content#107]
### Overview
We want to ensure all projects have the relevant tools for product management.  This issue will keep getting added to as we discover new 

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)

### Inventory Items

**Product**
- [ ] [Readme]()
- [ ] [Wiki]()
- [ ] [Google Drive]()
- [ ] [GitHub Repository]()
   - [ ] [Project Board]()
   - [ ] [Issue Templates]() 
- [ ] [Slack Channel]()
- [ ] 1Password
- [ ] Project Email
   - [ ] projectname@hackforla.org
   - [ ] projectname@gmail.com (You will need this for setting up some applications like MIro that use rate limiting. Do not send emails using this address) 
- [ ] [Team Roster]()
- [ ] [Product One Sheet]()
- [ ] [Recruitment Form]()
- [ ] [OKRs and WBS]()
- [ ] [Storypoints]()
- [ ] [Meeting Minutes Template]()

**Marketing**
   - [ ] [Marketing Objectives]()
      - [ ] Create new issue using this template: [Define Marketing Objectives for [INSERT PROJECT NAME]](https://github.com/hackforla/marketing/issues/new?assignees=&labels=Level%3A+Learning%2C+Skill%3A+Brand+Strategy%2C+Skill%3A+Digital+Marketing%2C+Skill%3A+Media+Strategy%2C+documentation&template=define-marketing-objectives-for--insert-project-name-.md&title=Define+Marketing+Objectives+for+%5BINSERT+PROJECT+NAME%5D+project)
      - [ ] Copy the link for the issue into the parentheses above
   - [ ] [Collect Marketing Assets]()
      - [ ] Create new issue using this template: [Collect Marketing Assets for [INSERT PROJECT NAME]](https://github.com/hackforla/marketing/issues/new?assignees=&labels=feature%3A+marketing+inventory+checklist&template=collect-marketing-assets-for--insert-project-name-.md&title=Collect+Marketing+Assets+for+%5BINSERT+PROJECT+NAME%5D)
      - [ ] Copy the link for the issue into the parentheses above
   
**UI/UX**
- [ ] [Figma]()
- [ ] [Miro]()
- [ ] [Presentation Deck]()
- [ ] [Competitive Analysis]()
- [ ] [User Persona/Journeys]()
- [ ] [Communication Style Guide (including documents, spreadsheets and forms)]()
- [ ] [User Research Guide/Template]()
- [ ] [Wireframes Template]()
- [ ] [Website analytics software setup]()

### Resources/Instructions
Google Excel sheet [Product Management Tracking Sheet](https://docs.google.com/spreadsheets/d/1OJOKJDhUzzMzaFwmbGoOdh5Ohh53LCwS4u7LulVvBsQ/edit#gid=1026078120)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.
