### ISSUE TITLE
GTM Team

### ISSUE THREAD

**Issue by ychu196** [hackforla/knowledgebase-content#114]
### Overview
As Hack for LA teams complete their digital products, they will need to develop a Go to Market strategy to launch their products into the marketplace to reach their intended audience.

However, there is a lack of knowledge, skills, experiences, and templates that can be leveraged.

We need GTM skills in:

- Strategic
- Operational
- Tactical

The purpose of this issue to develop a GTM or Go to Market strategy playbook, templates, and actionable resource that Hack for LA can use.

### Action Items

- [ ]  Establish interested PMs
- [ ]  Define requirements
- [ ]  Establish list of potential speakers
- [ ]  Templates required

The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions
Books:
- [Obviously Awesome](https://www.amazon.ca/Obviously-Awesome-Product-Positioning-Customers/dp/1999023005) by April Dunford; A book on Positioning
- [Go To Market Strategy: Advanced Techniques and Tools for Selling More Products, to More Customers, More Profitably](https://www.amazon.ca/Go-Market-Strategy-Lawrence-Friedman/dp/0750674601)
- [Playing to Win](https://www.amazon.ca/Playing-Win-Strategy-Really-Works/dp/1491528796)
- [Questions that Sell](https://www.google.ca/books/edition/Questions_that_Sell/y5E-DwAAQBAJ?hl=en&gbpv=1&printsec=frontcover)

Websites:
- [HBR GTM: 4 Questions to ask](https://entrepreneurship.hbs.edu/Documents/Session%20Summary/HBS%20Rock-%20Go-To-Market%20Strategy%20-%20FINAL.pdf)
- [Hubspot: Process for creating a GTM](https://blog.hubspot.com/sales/gtm-strategy)
- [LinkedIn Course on GTM](https://www.linkedin.com/learning/create-a-go-to-market-plan-2/create-your-go-to-market-plan?autoplay=true)

Videos:
- Peter Buscemi https://www.youtube.com/user/marketingprotemplate
- Overview of [B2B2C Business Model](https://youtu.be/KGNdj_Tv2HM?t=261) by FemTech Labs
- [Harvard Innovation Lab - GTM](https://www.youtube.com/watch?v=rqi-n0hA4uo)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.
