### ISSUE TITLE
Create a Guide/Template: Using GitHub Labels on HfLA Projects 

### ISSUE THREAD

**Issue by lasryariel** [hackforla/knowledgebase-content#115]
### Overview
We need to standardize certain types of labels across teams, so that there is more consistency when looking at issues across GitHub projects (for example standardizing the "role:" label helps the [hfla Open Roles project](https://github.com/orgs/hackforla/projects/67).
We will create a spreadsheet of standardized labels based on guidance to be outlined by Bonnie.

### Action Items

- [ ]  Bonnie to add guidance on standardized labels to this issue
- [x]  Ariel to prep initial spreadsheet
- [ ]  Bonnie to review
- [ ]  Make changes as needed based on Bonnie's feedback
- [ ]  Review with PM CoP

The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions

- Speadsheet [Standardized Github Labels](https://docs.google.com/spreadsheets/d/108VB9uZQj7hG-ESACNmR04eVKZ1XjSAB7nEuFIj0Zsg/edit?gid=0#gid=0)
- Ariel used [this wiki page](https://github.com/hackforla/website/wiki/Labels-and-Milestones) from the website team as a starting point

#### Guidance:

- Labels should be all lowercase
- Do not use hyphens for compound words that can use a space instead
- [Bonnie to add additional guidance here]

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.

**Comment by fchan218** [comment]
@lasryariel please provide update, if not then you will be removed as assignee

**Comment by Aditya23soni** [comment]
@fchan218 Added all the shortcuts
