### ISSUE TITLE
Create a Guide/Template: Personas, User story, User Journey template/examples

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/knowledgebase-content#117]
### Overview
Project Managers at Hack for LA need examples of how user stories are written, stored, used, etc.

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions
- Draft Guide Google Doc [Personas, User story, User Journey template/examples](https://docs.google.com/document/d/1ZzFeBBbtsL1HEC317zxRNZFMiv0wVtdsdIsSr1mDSKs/edit#heading=h.cn8wzyv0w6vs)
### Projects to Check (Hack for LA Examples)
- 100 Automations
   - [x] Provide link to user stories
   - [x] Provide text which explains how we have
      - [x] created them
      - [x] used them
      - [x] are evolving
   - Board: [100 Automations Personas, User Stories and Journeys WIP board](https://github.com/100Automations/Website/projects/2)
   - Details: [See our WIP wiki page describing the process with example images](https://github.com/100Automations/Website/wiki/Personas-User-Stories-Journeys)
- 311 Data
- Ballot Nav
- Food Oasis
- Civic Tech Index
- HomeUniteUs
- Record Clearance Project
- Undebate
- VRMS
- [YOUR PROJECT HERE]

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.
