### ISSUE TITLE
Create a Guide/Template: Consent Forms 

### ISSUE THREAD

**Issue by minar68** [hackforla/knowledgebase-content#131]
### Overview
We need to create a guide for  consent forms so that volunteers can use it as a template
### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions

 Google Drive Folder for this Guide’s documents and shortcuts (to documents in other locations)
 [0131 Consent Forms ](https://drive.google.com/drive/folders/19Jf2X2bi5lCox_24DtmXt51YB9uiCG41?usp=drive_link)

### Projects to Check
**List of projects that have used some kind of consent process:**
- Code for America: [Consent form Template from Code for America](https://docs.google.com/document/d/1Bkz69KKJ0FYz2Tb4T1AgGdT6af17aZLv)
- [x] Brigade playbook (Bonnie and Mari)
<details>
<summary>How the Brigade Organizer's Playbook (BOP) did consent on their project</summary>

<del>BOP Consent process and [interview instructions](https://docs.google.com/document/d/1cQumMP3mBUR595ZUkOgxoiLPkLL4WmgRWcAP_e3cWoQ/edit) (with etiquette) for the interviews</del>

1. [Email](https://docs.google.com/document/d/1ZjNE674nZXDPd2L7ULg_BEjdaOESwMB9exyBNeWakAM/edit)
2. Calendly where when they are picking the date of their interview we tell them the interview is recorded unless they need a scribe and to select now.
2. Beginning of Interview  using [Form/Script](https://docs.google.com/forms/d/e/1FAIpQLScis5UgFcNXKFxxioozsQVEJbQFuhE84W9W-Z3MQS_BQOseRA/formResponse)
![superman form consent 1](https://user-images.githubusercontent.com/37763229/126403163-ae4653cf-5292-4479-8a49-54d5cc7de0c9.PNG)

3. End of interview choices/confirmation using [Form/Script](https://docs.google.com/forms/d/e/1FAIpQLScis5UgFcNXKFxxioozsQVEJbQFuhE84W9W-Z3MQS_BQOseRA/formResponse)
![superman form concent 2](https://user-images.githubusercontent.com/37763229/126402965-d3d1f02e-7f8b-4684-adb2-935493558886.PNG)

</details>

- [ ] [Hack for LA's Website](https://github.com/hackforla/website) (Simone UX lead)
<details> 
<summary> Click here for details </summary>

- No consent forms found. [These were the resources checked](https://github.com/hackforla/website/issues?q=is%3Aissue+is%3Aopen+consent). <br>
- [Summary of communication](https://hackforla.slack.com/archives/C018FMQTWMT/p1653582950696439) 
</details>

- [ ] [GreenEarthOS](https://github.com/hackforla/climate-project) (Bonnie will tell you who to ask)
- [ ] [311 Data](https://github.com/hackforla/311-data) (Dana Chen was the UX lead) *
- [ ] [TDM Calculator](https://github.com/hackforla/tdm-calculator) (Shaeeka is the current UX lead but all the info about what was done when we interviewed users is here: https://github.com/hackforla/tdm-calculator/wiki/Usability-Testing-2021-05)
- [ ] [BallotNav](https://github.com/hackforla/ballotnav) (Karen is a PM she can tell you who to talk to)
- [ ] [Engage](https://github.com/hackla-engage) (Eli has been on the project longer than anyone, he is the tech lead) **
- [ ] [Expunge-Assist (formerly known as Record Clearance)](https://github.com/hackforla/expunge-assist) (Yumeng UX lead) **
- [ ] [Youth Justice Nav](https://github.com/hackforla/YouthJusticeNav/) (Ask Olivia who to ask on the team)

**List of projects that MIGHT have used some kind of consent process:**
- [ ] [Open Community Survey, main repo](https://github.com/hackforla/open-community-survey) (Ask JoAnne who to talk to)
   - [ ] [Open Community Survey, repo to review of empowerla.org website](https://github.com/hackforla/community-survey-empowerLA-website/) - EmpowerLA.org website (Bonnie) *
   - [ ] [Open Community Survey, repo to host NC website survey](https://github.com/hackforla/community-survey-nc-websites) - Neighborhood  Councils (Amy Wilkins) 
- [ ] [Civic Tech Jobs](https://github.com/hackforla/CivicTechJobs) (Ask Sharad who to ask)
- [ ] [Civic Tech Index](https://github.com/civictechindex/CTI-website-frontend) (Ask Levi who to ask)
- [ ] [Internship project](https://github.com/hackforla/intership) (Snigdha is UX lead)
- [ ] [Food Oasis](https://github.com/hackforla/food-oasis) (Ask Gigi and Benjamin PMs who to contact)
- [ ] [Access the Data](https://github.com/hackforla/access-the-data) (Ask Alyssa and Lucy PM who to contact)
- [ ] [VRMS](https://github.com/hackforla/vrms) (Ask Adam PM who to contact or if they have done it)
- [ ] [Design Systems](https://github.com/hackforla/design-systems) (ask Hana PM who to contact)
- [ ] [Lucky Parking](https://github.com/hackforla/lucky-parking) (Ask Greg, who to talk to)
- [ ] [100 Automations](https://github.com/100automations/website) (Ask Henry  PM who to talk to)

**Project that have not done user research yet**
- [Civic Tech Structure](https://github.com/hackforla/civic-tech-structure)
- [Guides](https://github.com/hackforla/guides) 
- [HomeUniteUs](https://github.com/hackforla/homeuniteus)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.

</p>
</details>

**Comment by ExperimentsInHonesty** [comment]
[Consent form Template from Code for America](https://docs.google.com/document/d/18PTtuHsur9epzweBlijDLZxihAxwGMrN/edit#heading=h.gjdgxs)

>Unable to view this document while moving this issue

This document issue is owned by Hack for LA, but is located in the Open Community Survey Project Google Drive.  I think for the purposes of this guide, we could copy it to our folder.
