### ISSUE TITLE
Guide: Giving qualitative feedback on design

### ISSUE THREAD

**Issue by daniellex0** [hackforla/knowledgebase-content#132]
### Overview
We need to create a guide for giving qualitative feedback on designs, so that volunteers at Hack for LA can learn effective practices in design critiques.

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [x] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [x]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [x]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [x]  If needed, create a template
- [x]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions

Guide : [UX/UI Designers: Give Qualitative Feedback](https://docs.google.com/document/d/1O45DnXZ6vVdmEI8At1b1oGkoWQjWAH8Z/edit)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.
