### ISSUE TITLE
Guide: Effective Practices for communicating with Product Managers

### ISSUE THREAD

**Issue by daniellex0** [hackforla/knowledgebase-content#133]
### Overview
We need to create a guide for effective communication between PM's and designers so that we can improve and optimize efficiency and communication channels

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [x] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [x]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [x]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [x]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions
Guide [UX Designers & Product Managers: Effective Communication Practices Guide](https://docs.google.com/document/d/1t1GWH4YJX0KfEBb-PSX-QureQT6tXroh3MaUfYBpTiQ/edit?tab=t.0#heading=h.gjdgxs)
### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.

**Comment by JesseTheCleric** [comment]
Guide Draft appears very far along in process, setting status at "sign off by peers" and can be kicked up or down from there
