### ISSUE TITLE
Guide: UX/UI Accessibility

### ISSUE THREAD

**Issue by daniellex0** [hackforla/knowledgebase-content#134]
### Overview
We need to create a guide for UX/UI Accessibility so that designers at Hack for LA can ensure their projects follow accessibility standards

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [x]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions
- [Draft How to UI/UX ACCESSIBILITY GUIDE ](https://docs.google.com/document/d/1oA3eHypGag_BbphTcUseKwaNWOvQ9gvClnWg2Atyqkk/edit?usp=sharing) - LAST UPDATE 08-13-2021 
- [Basic guidance for wcag website compliance](https://docs.google.com/document/d/1dFKJlIl5PGXzddXnm7dFCzFTReT8N9-HIq5DDvWlxQ8/edit?usp=sharing) 
- [accessibility guidance as part of the Design Systems project research](https://docs.google.com/document/d/1fUsbtr2m5oMhF_RkwDcEvl_3gykVsSXHWQC5EfAkoB4/edit)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.
