### ISSUE TITLE
Guide: How to Present Your Work (Design)

### ISSUE THREAD

**Issue by daniellex0** [hackforla/knowledgebase-content#137]
### Overview
We need to create a guide for how UX/UI designers should present their work, so that designers at Hack for LA can reference it and learn effective practices for presenting to stakeholders / managers / team members.

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [x] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [x]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [x]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions
Draft Guide [UX/UI Designers: Here’s how to present your work](https://docs.google.com/document/d/1DpGCa6tvYQrJb5Lmv2LggmCZeT8FEHj9/edit)

 Guide card Illustration and image credit information is in the [Toolkit page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967) (blue rectangle on bottom left)
### Projects to Check
- [100 Automations](https://github.com/100automations/website)
- [311 Data](https://github.com/hackforla/311-data)
- [Access the Data](https://github.com/hackforla/access-the-data)
- [BallotNav](https://github.com/hackforla/ballotnav)
- [Brigade Organizer's Playbook](https://github.com/codeforamerica/brigade-playbook)
- [Civic Tech Index](https://github.com/civictechindex/CTI-website-frontend)
- [Civic Tech Jobs](https://github.com/hackforla/CivicTechJobs)
- [Civic Tech Structure](https://github.com/hackforla/civic-tech-structure)
- [Data Science Projects](https://github.com/hackforla/data-science)
- [Design Systems](https://github.com/hackforla/design-systems)
- [Engage](https://github.com/hackla-engage)
- [Expunge-Assist (formerly known as Record Clearance)](https://github.com/hackforla/expunge-assist)
- [Food Oasis](https://github.com/hackforla/food-oasis)
- [GreenEarthOS](https://github.com/hackforla/climate-project)
- [Guides](https://github.com/hackforla/guides) 
- [HomeUniteUs](https://github.com/hackforla/homeuniteus)
- [Internship project](https://github.com/hackforla/internship)
- [Lucky Parking](https://github.com/hackforla/lucky-parking)
- [Open Community Survey](https://github.com/hackforla/open-community-survey)
- [People Depot](https://github.com/hackforla/peopledepot)
- [Tables team](https://github.com/hackforla/tables/)
- [TDM Calculator](https://github.com/hackforla/tdm-calculator)
- [VRMS](https://github.com/hackforla/vrms)
- [Hack for LA's Website](https://github.com/hackforla/website)
- [Youth Justice Nav](https://github.com/hackforla/YouthJusticeNav/)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.

**Comment by fchan218** [comment]
@Aditya23soni this is missing the google folder link

**Comment by Aditya23soni** [comment]
@fchan218 Done
