### ISSUE TITLE
Create a Guide/Template: Research Plan

### ISSUE THREAD

**Issue by minar68** [hackforla/knowledgebase-content#138]
### Overview
We need to create a guide for research plan so that people can use them 

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [x] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [x]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [x]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [x]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions

- [Guide: HOW TO - WRITE A RESEARCH PLAN ](https://docs.google.com/document/d/1ovSBNVkuizZD2EMOE2w522_x-sOAzQBEheMqfPWmQKk/edit#heading=h.c8tc614ce3iu)
- Research Plan Template [preview](https://docs.google.com/document/d/1lTmjiAzSwiUOFD4f4eGs0WGktaqZ6ogx_fiXhP7oR9U/preview) | [copy](https://docs.google.com/document/d/1lTmjiAzSwiUOFD4f4eGs0WGktaqZ6ogx_fiXhP7oR9U/copy)

- There was another issues related to this.  See if for any relevant details https://github.com/hackforla/knowledgebase-content/issues/98
- Template for Research plan and Guides can be accessed [here](https://drive.google.com/drive/folders/1zB8Z1zRR3duCFGwh73IsWRE4mU2uni0h?usp=sharing)

- [Original Guide: How to make a Research plan -draft with notes from interviews](https://docs.google.com/document/d/1lTmjiAzSwiUOFD4f4eGs0WGktaqZ6ogx_fiXhP7oR9U/edit?usp=sharing)

- How to make a research plan guidance [Developing a research plan](https://docs.google.com/document/d/1NP-ocqxpXJ__XZXDwkiTVIZlKy9yLOACnV2YaFcJBGU/edit)

- Projects that have made templates
   - [Open Community Survey](https://docs.google.com/document/d/1b8yYauonTH_XSDOpT9ALZMh1gfT7LcamHXa-UthFjkY/edit)
   - [Get Your Refund](https://docs.google.com/document/d/1oPbR_ErTPf24vr5h7fW3LsCQ87nOIp06nr_a5E0gO1k/edit)
   - [Design System](https://docs.google.com/document/d/1peRWmKWLpYEjqtlszfqmSSpsPm95qagnsFCJdiyereo/edit#heading=h.np7qv52pj0ao)
   - [Hypotheses building and validation process](https://docs.google.com/document/d/1vvEAe7fuphKk2nYRvOvX1IUr92QeQcl3DqtFZXRG2do/edit)
   - [CFA Qual research guide](https://f.hubspotusercontent30.net/hubfs/5622333/CFA_QualitativeResearchGuide_v1.pdf)

### Projects to Check
EmpowerLA.org website
[Green Earth OS - Research Plan: Funders [WIP] ](https://docs.google.com/document/d/1tsHUusJK5bZWjeiSFOsfdwbC-u-rJxRtkKWbNB0E814/edit)
[Green Earth OS-Research Plan - Previous Climate Projects Experience with Funding - 1.1](https://docs.google.com/document/d/143MYvgdetufZtXZQT4CfmAyRIbbnXPgg6wsMu6dq1UI/edit#heading=h.m9yajm4fzxzb)
[Green Earth OS -Research Plan - Criteria for Funders](https://docs.google.com/document/d/1s2g7r-1bONjKc3UsiiXF6TW23WA46XBjmEkdn-INyns/edit#heading=h.2yvcqzayafr6)
[Open Community Survey Research Plan](https://docs.google.com/document/d/1y5dIHcdvEp58D5S-3XtZm-d58i0Lk_tZ/edit)
[Hack for LA](https://docs.google.com/document/d/1EA5ZYHExu_RC8mfUAgxLxwJ-m_cMsGx_yAjE77gMXqw/edit)
[BOP Research Plan](https://docs.google.com/document/d/10Z90J2TPnoVy3cG96zawP4rw1eeyrdlahPYgHkbn3Pg/edit)
[Civic Opportunity Research Plan - WIP](https://docs.google.com/document/d/1pX829XB2s4IwNNw7AnhJggfgRaerBTAQz_8L0ZqaSKA/edit)
[TDM calculator slide deck that also contains the research brief](https://docs.google.com/presentation/d/1Cy5f1uDY7vW1vlsuDXdDvCpygUcQoct24VD6k0pRMGs/edit?userstoinvite=anushlok99@gmail.com&ts=607f4634&actionButton=1#slide=id.gc6ec7869ab_0_30)
[Access the Data](https://docs.google.com/document/d/1KLpwj5sYh8un7kvGeixg5VkSW1mR2OwhybIKbQFjh9Q/edit)
[Engage](https://docs.google.com/document/d/1_6shJLJwMnif5x0r2qJXG09G5SR1fPFtxqzS9g6OqmE/edit)
[Food Oasis](https://docs.google.com/document/d/13yg8Be13S62KyjrPv4J3nguIqBsgzFq3H1ionumbyQc/edit)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.

**Comment by fchan218** [comment]
@kamiladuncan please provide update. if not then you will be removed as assignee

**Comment by fchan218** [comment]
@Aditya23soni this is missing google folder link

**Comment by Aditya23soni** [comment]
@fchan218 Done!
