### ISSUE TITLE
Create a Guide: Card Sorting

### ISSUE THREAD

**Issue by tan-zhou** [hackforla/knowledgebase-content#140]
### Overview
We need to create a guide for doing card sorting so that members at Hack for LA know when and how to use the method.

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [x] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions

- [Card Sorting Beginner’s Guide...; Smashing Magazine](https://www.smashingmagazine.com/2014/10/improving-information-architecture-card-sorting-beginners-guide/)
- [Card Sorting:A Definitive Guide; Boxes and Arrows](https://boxesandarrows.com/card-sorting-a-definitive-guide/)
- [Card Sorting: Uncover Users' Mental Models..; NNG](https://www.nngroup.com/articles/card-sorting-definition/)
- [Card Sorting: Your guide...;Maze](https://maze.co/guides/card-sorting/#:~:text=Hybrid%20card%20sorting%20is%20a,can%20also%20create%20new%20categories.)
- [Card Sorting 101; Optimal Workshop](https://www.optimalworkshop.com/learn/101s/card-sorting/)
- [How to Run an Effective Card Sort...;dscout](https://dscout.com/people-nerds/card-sorting)

### Projects to Check
- [100 Automations](https://github.com/100automations/website)
- [311 Data](https://github.com/hackforla/311-data)
- [Access the Data](https://github.com/hackforla/access-the-data)
  - https://github.com/hackforla/access-the-data/issues/77#issue-1005996669
  - https://github.com/hackforla/access-the-data/issues/36#issue-967743721
- [BallotNav](https://github.com/hackforla/ballotnav)
- [Brigade Organizer's Playbook](https://github.com/codeforamerica/brigade-playbook)
   - https://github.com/codeforamerica/brigade-playbook/issues/127#issue-777522612
- [Civic Tech Index](https://github.com/civictechindex/CTI-website-frontend)
- [Civic Tech Jobs](https://github.com/hackforla/CivicTechJobs)
- [Civic Tech Structure](https://github.com/hackforla/civic-tech-structure)
- [Data Science Projects](https://github.com/hackforla/data-science)
- [Design Systems](https://github.com/hackforla/design-systems)
- [Engage](https://github.com/hackla-engage)
- [Expunge-Assist (formerly known as Record Clearance)](https://github.com/hackforla/expunge-assist)
- [Food Oasis](https://github.com/hackforla/food-oasis)
   - [FOLA: Research Plan: Volunteer interface: Card Sort](https://docs.google.com/document/d/12NsrDd_4e3WcZ3OiwyTuMpoedLt1tbTdA7qoHLtN1VA/edit#)
- [GreenEarthOS](https://github.com/hackforla/climate-project)
- [Guides](https://github.com/hackforla/guides) 
- [HomeUniteUs](https://github.com/hackforla/homeuniteus)
- [Internship project](https://github.com/hackforla/intership)
- [Lucky Parking](https://github.com/hackforla/lucky-parking)
- [Open Community Survey](https://github.com/hackforla/open-community-survey)
- [TDM Calculator](https://github.com/hackforla/tdm-calculator)
   - https://github.com/hackforla/tdm-calculator/issues/57#issue-480921773
- [VRMS](https://github.com/hackforla/vrms)
- [Hack for LA's Website](https://github.com/hackforla/website)
- [Youth Justice Nav](https://github.com/hackforla/YouthJusticeNav/)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.
