### ISSUE TITLE
Create a Guide/Template: CI/CD with GitHub actions

### ISSUE THREAD

**Issue by BeckettOBrien** [hackforla/knowledgebase-content#152]
### Overview
We need to create a guide to making effective CI/CD pipelines with GitHub actions so that developers can write their own workflows to speed up the development process.

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions
Google Drive Folder for this Guide’s documents and shortcuts (to documents in other locations) [0152 [DRAFT] CI/CD with GitHub actions](https://drive.google.com/drive/folders/1fR5W5w3Sqb3UPTMvw_YSbp70cflXOGt7)
### Projects to Check
- [x] [100 Automations](https://github.com/100automations/website)
- [x] [311 Data](https://github.com/hackforla/311-data)
- [x] [Access the Data](https://github.com/hackforla/access-the-data)
- [x] [BallotNav](https://github.com/hackforla/ballotnav)
- [x] [Brigade Organizer's Playbook](https://github.com/codeforamerica/brigade-playbook)
- [x] [Civic Tech Index](https://github.com/civictechindex/CTI-website-frontend)
- [x] [Civic Tech Jobs](https://github.com/hackforla/CivicTechJobs)
- [x] [Civic Tech Structure](https://github.com/hackforla/civic-tech-structure)
- [x] [Data Science Projects](https://github.com/hackforla/data-science)
- [x] [Design Systems](https://github.com/hackforla/design-systems)
- [x] [Engage](https://github.com/hackla-engage)
- [x] [Expunge-Assist (formerly known as Record Clearance)](https://github.com/hackforla/expunge-assist)
- [x] [Food Oasis](https://github.com/hackforla/food-oasis)
- [x] [GreenEarthOS](https://github.com/hackforla/climate-project)
- [x] [Guides](https://github.com/hackforla/guides) 
- [x] [HomeUniteUs](https://github.com/hackforla/homeuniteus)
- [x] [Internship project](https://github.com/hackforla/internship)
- [x] [Lucky Parking](https://github.com/hackforla/lucky-parking)
- [x] [Open Community Survey](https://github.com/hackforla/open-community-survey)
- [x] [People Depot](https://github.com/hackforla/peopledepot)
- [x] [Tables team](https://github.com/hackforla/tables/)
- [x] [TDM Calculator](https://github.com/hackforla/tdm-calculator)
- [x] [VRMS](https://github.com/hackforla/vrms)
- [x] [Hack for LA's Website](https://github.com/hackforla/website)
- [x] [Youth Justice Nav](https://github.com/hackforla/YouthJusticeNav/)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.
