### ISSUE TITLE
Create a Guide/Template: How To Check and Sync Your Device's Time

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/knowledgebase-content#4]
### Overview
We need to create a guide for how to check your device's time is accurate using Time.is and how to fix it if the time is inacu.

### Action Items
~- [ ] Gather examples of how other Hack for LA projects have done, adding each example as a link in the resources section. It is really important to annotate as you go in this issue, so that if you have to stop working on the issue, its already up to date with your findings.~
   ~- [ ] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label~
~- [ ] Create a draft template, either in markdown format in this issue or a google doc in the [product management google drive>Product Management Guides](https://drive.google.com/drive/folders/1u9YOTWevHwEiHP8-r8d00rlqOn6q8e-5?usp=sharing)~
    ~- [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label~
- [x] Create a guide on how to use the template 
   - [x] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
~- [ ] Possibly create an issue template on .github~ 
   ~- [ ] Include link to template under resources if you add it as a template in .github~
- [ ] Update issue hackforla/product-management#128 with the name of item you are working

### Resources
- Refer to hackforla/product-management#123 for how to write a guide and the guide template
- Update issue hackforla/product-management#128 with the name of item you are working
- Files for _Guide: How to Sync Your Device's Time_
  - [Folder](https://drive.google.com/drive/folders/1PfG2xv-Qs3jq1iDHumHPzsb-IZW45MCd)
    - [Guide](https://docs.google.com/document/d/1fWMeVqpR2pkwl_70G78blXWIs2yMNftzXlTePk-McuE/edit#heading=h.c8tc614ce3iu)
    - [Graphics and Annotations slide deck](https://docs.google.com/presentation/d/1z_wevnh_Ai-XvPssPPoFqKjQM6Yri_vH5KfjABptWUk/edit#slide=id.gcd84038bdd_0_0)
    - [Header](https://docs.google.com/drawings/d/1zGfuvV6VnMq6We2M_JIqMQrW25tT_ZgQ_leKTGMB2ZY/edit)

### Notes
- Gathering Examples: Time syncing is needed mainly for using 1Password's one-time password feature. Also, Bonnie told me no projects currently use 1Password's One-Time Password for signing in. Thus, there is no examples to gather for time syncing.
- Draft Template: There is no template to be created because this is a guide for how to check and sync a computer's time.

**Comment by ExperimentsInHonesty** [comment]
<details><summary>Prior version of issue</summary>
<p>

### Overview
We need to create a guide for how to check your device's time is accurate using Time.is and how to fix it if the time is inacu.

### Action Items
~- [ ] Gather examples of how other Hack for LA projects have done, adding each example as a link in the resources section. It is really important to annotate as you go in this issue, so that if you have to stop working on the issue, its already up to date with your findings.~
   ~- [ ] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label~
~- [ ] Create a draft template, either in markdown format in this issue or a google doc in the [product management google drive>Product Management Guides](https://drive.google.com/drive/folders/1u9YOTWevHwEiHP8-r8d00rlqOn6q8e-5?usp=sharing)~
    ~- [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label~
- [x] Create a guide on how to use the template 
   - [x] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
~- [ ] Possibly create an issue template on .github~ 
   ~- [ ] Include link to template under resources if you add it as a template in .github~
- [ ] Update issue hackforla/product-management#128 with the name of item you are working

### Resources
- Refer to hackforla/product-management#123 for how to write a guide and the guide template
- Update issue hackforla/product-management#128 with the name of item you are working
- Files for _Guide: How to Sync Your Device's Time_
  - [Folder](https://drive.google.com/drive/folders/1PfG2xv-Qs3jq1iDHumHPzsb-IZW45MCd)
    - [Guide](https://docs.google.com/document/d/1fWMeVqpR2pkwl_70G78blXWIs2yMNftzXlTePk-McuE/edit#heading=h.c8tc614ce3iu)
    - [Graphics and Annotations slide deck](https://docs.google.com/presentation/d/1z_wevnh_Ai-XvPssPPoFqKjQM6Yri_vH5KfjABptWUk/edit#slide=id.gcd84038bdd_0_0)
    - [Header](https://docs.google.com/drawings/d/1zGfuvV6VnMq6We2M_JIqMQrW25tT_ZgQ_leKTGMB2ZY/edit)

### Notes
- Gathering Examples: Time syncing is needed mainly for using 1Password's one-time password feature. Also, Bonnie told me no projects currently use 1Password's One-Time Password for signing in. Thus, there is no examples to gather for time syncing.
- Draft Template: There is no template to be created because this is a guide for how to check and sync a computer's time.

</p>
</details>

**Comment by fchan218** [comment]
<details><summary>Prior version of issue</summary>
<p>

### Overview
We need to create a guide for how to check your device's time is accurate using Time.is and how to fix it if the time is inacu.

### Notes


### Overview
We need to create a guide for how to check your device's time is accurate using Time.is and how to fix it if the time is inaccurate

### Details
- Gathering Examples: Time syncing is needed mainly for using 1Password's one-time password feature. At the time of this original writing, no projects were using 1Password's One-Time Password for signing in. So, there were no examples to gather for time syncing at the time..
- Draft Template: There is no template to be created because this is a guide for how to check and sync a computer's time.

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labelled 'Tasks' at the bottom of this issue, and complete each task listed.

- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ] [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ] [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
  - [ ] If needed, create a template 
- [ ] [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ] [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)

### Resources/Instructions
- [Guide: How to Check and Sync Your Device's Time](https://docs.google.com/document/d/1fWMeVqpR2pkwl_70G78blXWIs2yMNftzXlTePk-McuE/edit#heading=h.c8tc614ce3iu)

### Projects to Check
N/A

### Tasks
- [x] **Gathering Examples with GitHub**
Follow the instructions from the slide deck Part 1: [Gathering Examples With GitHub: Wiki, Issues, Project Board, Resources Provided](https://docs.google.com/presentation/d/1XWY-OMiomzpKw_aCL1JkdgAhqpgGDZ2bu_XuReTO1zw/edit#slide=id.g150e30fd48b_0_443)
  - Remove the following labels from your issue as you complete them:
     - [x] status: needs wiki examples
     - [x] status: needs issues examples
     - [x] status: needs project board examples
  - Congrats you have completed Part 1: Gathering Examples With GitHub: Wiki, Issues, Project Board, Resources Provided
     - [x] Go to [Gather Examples, Use GitHub Search](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples#use-github-search) and copy it below
- [x] **Gathering Examples with Github Search**
Follow the instructions from the slide deck Part 1.5: [How to Use Github Search](https://docs.google.com/presentation/d/1M2f2Q9vefNAzQ4lvcw13x-7McPbrb8NZIVFgJUrefzE/edit?usp=sharing)
  - [x] Complete the activities inside the deck
  - Congrats! You have completed part 1.5: How to Use Github Search. 
    - [x] Go to [Gather Examples with Slack](https://github.com/hackforla/guides/wiki/Gathering-Examples-with-Slack) and copy it below
- [x] **Gathering Examples with Slack**
Follow the instructions from the slide deck Part 2: [Gathering Examples With Slack](https://docs.google.com/presentation/d/1-Kg7yLRXsdGo4Ln8L-WiunOOO3Uc7TuXvH5afcp3AKQ/)
  - Remove the following labels from your issue as you complete them:
    - [x] status: needs slack examples
    - [x] Phase: 1 - Gather Examples Solo
  - Congrats! You have completed Part 2: Gathering Examples with Slack
    - [x] Go to [Phase 2 - Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively) and copy it below
</p>
</details>

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the Product Repo:</summary>
<p>

<img width="350" alt="Screenshot 2024-09-26 at 5 43 27 PM" src="https://github.com/user-attachments/assets/4bec5ec0-9fb0-43d2-b49d-475b40943184">
</p>
</details>

**Comment by fchan218** [comment]
### Files in this Issue:
https://docs.google.com/document/d/1fWMeVqpR2pkwl_70G78blXWIs2yMNftzXlTePk-McuE/edit#heading=h.c8tc614ce3iu
- This file will need to be moved to the knowledgebase-content Google Drive

**Comment by fchan218** [comment]
@JessicaLucindaCheng  This guide issue is moving to the knowledgebase-content repo. If you would like to maintain edit access to the issue and its associated files, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69).

**Comment by JessicaLucindaCheng** [comment]
@fchan218 

> @JessicaLucindaCheng This guide issue is moving to the knowledgebase-content repo. If you would like to maintain edit access to the issue and its associated files, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69).

Thanks for letting me know! I have filled out the form.

**Comment by JessicaLucindaCheng** [comment]
> We need to remove the label cop: product and add cop: admin and move the shortcut

- [x] Remove label cop: product
- [x] Add cop: admin
- [ ] Move the shortcut

**Comment by fchan218** [comment]
shortcuts are added to correct CoPs
