### ISSUE TITLE
Create a Guide/Template: Brand Sprint for your project

### ISSUE THREAD

**Issue by erigilg** [hackforla/knowledgebase-content#5]
### Overview
We need to create a guide to using size labels so teams can accurately assess how long tasks should take to complete.

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labelled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.

**Comment by ExperimentsInHonesty** [comment]
@JesseTheCleric This issue is ready to move. There are no files to move, but you still need to create the folders for it and link the folder in this issue.

**Comment by ExperimentsInHonesty** [comment]
This is a duplicate of 
- https://github.com/hackforla/knowledgebase-content/issues/89

89 is further along.

Next steps for this issue is 
- [x] Identify all the folders
- [x] Mark the folder as deprecated and add any shortcuts needed
- [x] add a link in the folder to the 89 folder
- [x] close this issue as duplicate

**Comment by ExperimentsInHonesty** [comment]
Folders: 
- [Guides > By Title](https://drive.google.com/drive/folders/1I3wAeJIXgzA7IcTusm8QXIIkH7WJ4z6P) 
   - The 005 guide folder has been renamed to [005 [DRAFT] Brand Sprint for Your Project - depreciated - replaced by 089](https://drive.google.com/drive/folders/1Dh1-5Nui4yf3ieNI8SlSwcmbWLmUo9MC)
   - There is a shortcut in the folder to 089 called 0089 [DRAFT] Building a Brand Book through Team Exercises (this is the replacement for 005)
- [Guides > By Issue No](https://drive.google.com/drive/folders/1aN5PWR8VKWavfhOjngpP9cmenzSh0EMk) Has shortcut.  
   - The shortcut has been renamed to 005 [DRAFT] Brand Sprint for Your Project - depreciated - replaced by 089
