### ISSUE TITLE
Create a Guide/Template: UX Researcher Glossary

### ISSUE THREAD

**Issue by daniellex0** [hackforla/knowledgebase-content#54]
### Overview
We need to create a guide for a UX Researcher's Glossary so that new UX Researchers at Hack for LA can quickly become familiar with the most common terminology

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions
[Usability.gov UX Research glossary](https://www.usability.gov/what-and-why/glossary/tag/user-research/index.html)
[UX Glossary](https://ferpection.com/en/ux-glossary/)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.

**Comment by knqti** [comment]
Slack example:

![2024-12-13 15_51_31-home-unite-us-uxresearch](https://github.com/user-attachments/assets/b9b6a497-5854-4310-935b-1cca9657df20)

**Project**: HomeUniteUs
**Source**: #home-unite-us-uxresearch

**Comment by knqti** [comment]
<details>
   <summary>Need access to the following</summary>

- [0054 UX Researcher Glossary](https://drive.google.com/drive/folders/1GJ9hEEmodCixV7AT5QgIAOJtQ7CGfi4K?usp=drive_link)
- [Glossary](https://docs.google.com/document/d/1rVZE1c3G2xfB6Z_-2pAFgiToKm64lK_KHLgIhq7YZYU/edit#heading=h.obaa8a1h4lt2)
- [UXR Glossary](https://docs.google.com/document/d/1D19tbPqQkFzHYF2GemsZDDdMjbUM6jh6E6ArYWS-WIo/edit)
- [Archived content glossary #1](https://docs.google.com/document/d/1wJVO0tgkG3S8CZd8N3KNbFXFbJREo-JZ7NfK_RNwA7Y/edit)
- [Archived content glossary #2](https://docs.google.com/document/d/1tc1RLRfibfAkwKStQFuU0P_Iy5KrA_dkSnQrTvdOPXI/edit)
- [Glossary spreadsheet](https://docs.google.com/spreadsheets/d/10jUOU43P1pCysTDKKR6mlxtvJ62iXq5IrcJWm2N9zGk/edit?gid=0#gid=0)
- [Guides: Glossary spreadsheet](https://docs.google.com/spreadsheets/d/175pDnr-izub36J0xya6m9rSfIico6XnsStUz9KHSWIA/edit)
- [Google Sheets glossary](https://docs.google.com/spreadsheets/d/1HBeTCkkbiKRlbjAb2BUkeW4F9G2gnbzBmfWbu1NQ6RI/edit?gid=0#gid=0)
- [TDM Glossary Draft](https://docs.google.com/spreadsheets/d/1LxACA2eworqV6MG0xll_MFz6DlwEfQqBa1lG03C4Xgo/edit#gid=0)
- [Terms Already Defined in the HfLA Glossary](https://docs.google.com/spreadsheets/d/1LxACA2eworqV6MG0xll_MFz6DlwEfQqBa1lG03C4Xgo/edit#gid=1814646988)

</details>

**Comment by knqti** [comment]
<details>
<summary>Misc. notes to keep track of findings.</summary>

# Phase 1

## Current glossaries

Name                 | Format
----------------- | -----------------
Access the Data | GitHub Wiki
Civic Tech Index | GitHub Wiki
Expunge-Assist  | Google Doc
Food Oasis         | Google Sheet
Guides                | GitHub Wiki, Google Sheet
HomeUniteUs    | GitHub Wiki, Google Sheet
Tech Work Exp.  | Google Sheet
TDM Calculator | Google Sheet
Product              | Google Sheet

**GitHub Wiki**

Pros:
- Lives within the project's repository
- Integrates with other knowledge content as a Wiki

Cons:
- Requires knowledge of GitHub and Markdown
- Collaboration requires git, fork, PR, etc.

**Google Sheet/Doc**

Pros:
- Easier to setup, edit, and share
- Simple collaboration tools

Cons:
- Lives outside the project's repository
- Can be misplaced and/or duplicated as members change
- (Doc) Not ideal for large glossaries and table formats


</details>

**Comment by knqti** [comment]
Counterpart Contacts
- UI/UX: Aparna Gopal
![image](https://github.com/user-attachments/assets/fc62fbc9-0bc1-4d2c-8648-a940cb0ffa50)

**Comment by ExperimentsInHonesty** [comment]
- Made copies of all of the documents in folders that were inaccessible to Kevin (as a guide maker), and put them into the folder for this guide ([0054 UX Researcher Glossary](https://drive.google.com/drive/folders/1GJ9hEEmodCixV7AT5QgIAOJtQ7CGfi4K?usp=drive_link)).  
- Added this text to each of the copies with a link back to the original in case needed
```
This document is a copy for the purposes of make a guide and can be deleted when done.  The original is here:
```

**Comment by ExperimentsInHonesty** [comment]
Bonnie will 
- finish editing the glossary for twe [TWE: Wiki Glossary Draft, filtered by items that still need signoff](https://docs.google.com/spreadsheets/d/10omnFb1L8lM4n4Rz610UzI1E51ZMRG6tuVnphrYnay0/edit?gid=0#gid=0&fvid=885331144)
- create HfLA parent glossary
   - one parent page with a column that has all relevant cops in it
   - tabs for each cop (formula that pulls all terms relevant for that cop from the parent)
- create Template from example: [Copy of TDM: Glossary Draft](https://docs.google.com/spreadsheets/d/1oZ-Z6iUxLDlYoheORiu4LEnARByAHl78t5i-ne3pbDY/edit?gid=0#gid=0)
   - formula to pull all terms from parent, and by COP

**Comment by ExperimentsInHonesty** [comment]
I am updating this issue title to be a generic glossary, not specific to any Practice Area or CoP

**Comment by fchan218** [comment]
@knqti this is delayed due to Bonnie unable to review and create the parent glossary for Kevin to work on the guide

**Comment by ExperimentsInHonesty** [comment]
- [HfLA Glossary](https://docs.google.com/spreadsheets/d/1dyzQzBpEK1dRmem068_XGqEuW1brk83cncRgZIDtix4/) - edit version
- [HfLA Glossary](https://docs.google.com/spreadsheets/d/1dyzQzBpEK1dRmem068_XGqEuW1brk83cncRgZIDtix4/preview) - preview version (what should be given to everyone)

**Comment by knqti** [comment]
### Updates

Rough draft guide is WIP.

Updated [HfLA: Wiki Glossary](https://docs.google.com/spreadsheets/d/1dyzQzBpEK1dRmem068_XGqEuW1brk83cncRgZIDtix4/edit?gid=0#gid=0) `FILTER` formulas to named ranges for readability.

e.g., `=FILTER(EntireSheet, RelatedToPM=TRUE)`

### Suggestions

[[PROJECT NAME]: Wiki Glossary Draft](https://docs.google.com/spreadsheets/d/10Cg00-OzbwykHXmXxeA6V2DtHG0gAlxNQTZwq4-j4n8/edit?usp=drive_link) be added as a sheet within HfLA: Wiki Glossary. This consolidates into 1 file. Might also make it easier to transfer data instead of using `QUERY/IMPORTRANGE`.

**Comment by ExperimentsInHonesty** [comment]
Updated and signed off on two more terms

**Comment by knqti** [comment]
### 2025-02-28 Meeting

- Project Glossary (template) pulls data from HfLA Glossary (parent)
- Project Glossary will have three sheets: 
    (1) Terms from HfLA Glossary
    (2) Terms from Project Glossary
    (3) Terms from both HfLA Glossary and Project Glossary
- Teams will fill out sheet (3) with **new** terms for their project

To-do:

- [ ] Create formula to pull in data for sheet (1)
- [ ] Create formula to pull in data for sheet (2)
- [ ] Create formula to pull in data for sheet (3)

**Comment by knqti** [comment]
[Project Glossary (template)](https://docs.google.com/spreadsheets/d/10Cg00-OzbwykHXmXxeA6V2DtHG0gAlxNQTZwq4-j4n8/edit?gid=0#gid=0) updates:

- Sheet (1) converted into table `HflaGlossary`. Created formula:
`=QUERY(IMPORTRANGE("https://url", "Glossary-All terms!A3:K"), "SELECT Col1, Col2, Col10, Col11")`
- Sheet (2) converted into table `ProjectGlossary`. No formula needed because users will manually fill this sheet out.
- Sheet (3) created formula:
`=UNIQUE({HflaGlossary; ProjectGlossary})`

**Comment by knqti** [comment]
### 2025-03-14 Meeting

-  "project glossary-input" users will manually update this sheet only
    - Need to bring in the approval columns from "Glossary-All terms"
- "hfla glossary" bring in the CoP options and hide/protect in production
- "Glossary-All terms" will need filter options for different CoPs (or a way for them to make their own)
- Fix visual branding

**Comment by Rabia2219** [comment]
@knqti 
Hi Kevin,
You can skip the meeting tomorrow as we will not be able to review your issue.
If you have any questions, please leave them on a comment in the issue. Thanks!

**Comment by knqti** [comment]
@Rabia2219 
1. Progress: Rough framework with formulas are complete. Working on a way for users to easily filter views between different CoP terms.
2. Blockers: n/a
3. Availability: 3/28 at 7:30AM PT
4. ETA: 4/2 template ready to be reviewed

**Comment by knqti** [comment]
### 2025-03-28 Meeting

- [ ] "project glossary-input" need a CoP column for users to select. This will need to auto populate in "Glossary-All terms" and work with the custom filter views
- [ ] The original HfLA Glossary spreadsheet needs a new tracker tab. This will track new glossary's URL and number of terms
- [ ] Need a system to approve new terms into the original HfLA Glossary spreadsheet

**Comment by ExperimentsInHonesty** [comment]
@knqti Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary):

**Comment by knqti** [comment]
## 2025-05-01 update
 
1. Progress: Updated guide with template instructions section.
2. Blockers: 
    - Need a formula to parse out new terms from a project glossary's URL
    - Limited internet access this month
3. 1 hour
4. 2-3 weeks

**Comment by knqti** [comment]
## 2025-05-26 update

1. Progress: 
    - Updated the HfLA: Glossary's sheet "Instructions and Links"
    - Project Tracker takes a project glossary's URL and checks the sheet "Project Glossary (input)" for any new terms
2. Blockers: Update drafted guide for review
3. Availability: Weekly
4. ETA: 2025-05-30

**Comment by knqti** [comment]
@ExperimentsInHonesty 

>> 1. Project Glossaries: Enter the project name
>
> Sounds straightforward. If my project was TDM Calculator, that is what I would put there

Yes that is correct.

>> 2. Project URL: Enter the URL provided by the project lead
> 
> I think this would be the URL of the TDM glossary. Is that correct?

Yes that is correct. I've updated it so that the link from B12 gets automatically pulled into D12. 

> > 3. Has New Terms: Drag the formula from above into your row - this will indicate if there are new terms
> 
> Sounds straightforward. This is just checking if there are items in column D.

Yes that is correct.

> > 4. Terms: Drag the formula from above into your row - this will automatically show any new terms
> 
> What does this do?

This looks at [Project Glossary (input)](https://docs.google.com/spreadsheets/d/10Cg00-OzbwykHXmXxeA6V2DtHG0gAlxNQTZwq4-j4n8/edit?pli=1&gid=107052018#gid=107052018) column A's terms and checks if any of them exist in [Glossary-All terms](https://docs.google.com/spreadsheets/d/1dyzQzBpEK1dRmem068_XGqEuW1brk83cncRgZIDtix4/edit?pli=1&gid=0#gid=0) column A. If they do not exist, then the terms are displayed as comma-separated values under New Terms column D. You'll see the term "Blocker" is not displayed because it already exists in Glossary-All terms.

**Project Glossary (input)** | **Glossary-All terms** | **Instructions and Links**
--- | --- | ---
![Image](https://github.com/user-attachments/assets/e9e19953-93ea-4c65-8e3a-fd9125a9d2a2) | ![Image](https://github.com/user-attachments/assets/3b0ce613-d2e4-4437-b1e0-0c6e53da06ed) | ![Image](https://github.com/user-attachments/assets/a8f56780-1dfb-4a8f-a692-e690c1986a79)

**Comment by ExperimentsInHonesty** [comment]
@knqti ok, thanks for the prior answers.

### New tasks and notes based on my review of the Guide and glossary templates
- [ ] 1: On the [[PROJECT NAME]: Wiki Glossary Draft, tab: Glossary-All terms (HfLA  & Project)](https://docs.google.com/spreadsheets/d/10Cg00-OzbwykHXmXxeA6V2DtHG0gAlxNQTZwq4-j4n8/edit?pli=1&gid=0#gid=0) it has blocker in red, because since it's a duplicate it triggers the conditional formatting.  Which seems like a good idea, but on the [[PROJECT NAME]: Wiki Glossary Draft, tab: Project Glossary (input)](https://docs.google.com/spreadsheets/d/10Cg00-OzbwykHXmXxeA6V2DtHG0gAlxNQTZwq4-j4n8/edit?pli=1&gid=107052018#gid=107052018) where they will actually put the new term, it doesn't seem to check anywhere that it's a duplicate.  

   I think it would help if there was a column on the input page that checked to see if the term was already there and gave a message of some sort (e.g., this term will be reviewed by Admin team, or duplicate term, already in glossary)

- 2: I am not sure if we discussed this already for feasibility.  But I believe that we should lock the following tabs in [[PROJECT NAME]: Wiki Glossary Draft](https://docs.google.com/spreadsheets/d/10Cg00-OzbwykHXmXxeA6V2DtHG0gAlxNQTZwq4-j4n8), so that the only tab they can edit is Project Glossary (input).  I tried just locking it with a warning and it works, so I left it on.  We could increase the locking in the future, to a select set of emails (me, and the hfla-email-all@hackforla.org email).  Unless you think it will stop working when they move the copy from the template to their project drive.
   - hfla glossary
   - Glossary-All terms (HfLA  & Project)
   - Instructions and Links

- [ ] 3: The title of the tab, in [[PROJECT NAME]: Wiki Glossary Draft](https://docs.google.com/spreadsheets/d/10Cg00-OzbwykHXmXxeA6V2DtHG0gAlxNQTZwq4-j4n8), called "hfla glossary" should be changed to "HfLA Glossary" unless there was a reason why it's lowercase.

- [ ] 4: On the [[PROJECT NAME]: Wiki Glossary Draft, tab: Project Glossary (Input)](https://docs.google.com/spreadsheets/d/10Cg00-OzbwykHXmXxeA6V2DtHG0gAlxNQTZwq4-j4n8/edit?pli=1&gid=107052018#gid=107052018), I would like them to indicate if they think it's a project term or a HfLA term.  Otherwise, the [HfLA: Glossary, tab: Instructions and Links](https://docs.google.com/spreadsheets/d/1dyzQzBpEK1dRmem068_XGqEuW1brk83cncRgZIDtix4/edit?gid=1340595979#gid=1340595979) Project Tracker table, New Terms column, is likely to fill up with terms we don't need to look at, at the org level and that risks us missing a term we do need to add to the HfLA Glossary.

   - [ ] Additionally, I added some instructions to [HfLA: Glossary, tab: Instructions and Links](https://docs.google.com/spreadsheets/d/1dyzQzBpEK1dRmem068_XGqEuW1brk83cncRgZIDtix4/edit?gid=1340595979#gid=1340595979) for how to process new terms, which includes this text on row 13 "1) Go to the Project Glossary, tab: Project Glossary (input) and review the terms details, if it's not applicable to HfLA, make sure it has the indication that it's for the project only."  So once you change the [[PROJECT NAME]: Wiki Glossary Draft, tab: Project Glossary (Input)](https://docs.google.com/spreadsheets/d/10Cg00-OzbwykHXmXxeA6V2DtHG0gAlxNQTZwq4-j4n8/edit?pli=1&gid=107052018#gid=107052018) to have the indicator I mentioned, please revise that instruction to be more specific

- [ ] 5: On [HfLA: Glossary, tab: Instructions and Links](https://docs.google.com/spreadsheets/d/1dyzQzBpEK1dRmem068_XGqEuW1brk83cncRgZIDtix4/edit?gid=1340595979) I think the title of the table cell "Project URL", should be changed to "Project Glossary (input) URL".  I would have changed it, but I didn't know if it would break anything.  Please change and update instruction 3 on row 8.

- 6: I created a new tab [[PROJECT NAME]: Wiki Glossary Draft, tab: Instructions and Links](https://docs.google.com/spreadsheets/d/10Cg00-OzbwykHXmXxeA6V2DtHG0gAlxNQTZwq4-j4n8/edit?pli=1&gid=18170496999).  I have added everything I think we need, in terms of instructions.  I also added two new tables, so that when I process the terms from their input sheet, I can remove them from the input sheet but still have a place to put the history of what I have done, so that they are incentivized to keep providing new terms and are not confused about where the content they submitted went.  And so that their Project Glossary (input) table only retains their Project Glossary terms.

- 7: in [Guide: Create a Glossary](https://docs.google.com/document/d/1EjPdkq_mHHUi6tXk22c7MrLTWwrvbAMw0_Oi5fYRIu0) there are two outstanding comments
   - [ ] [Comment 1](https://docs.google.com/document/d/1EjPdkq_mHHUi6tXk22c7MrLTWwrvbAMw0_Oi5fYRIu0/edit?disco=AAABlTc4A7U): On page two I highlighted the header and left the comment "Please use [How to Add Screenshots and Graphics in Guides](https://docs.google.com/document/d/1OyPfKqUU7ZinhjMoRmsXywyZfME_Oo_hpC2Zdxlb310) to add the blue header"
   - [ ] [Comment 2](https://docs.google.com/document/d/1EjPdkq_mHHUi6tXk22c7MrLTWwrvbAMw0_Oi5fYRIu0/edit?disco=AAABllQdH68): On page 5 Under Template Instructions: [PROJECT NAME]: Wiki Glossary step 4: text "They can use the last three columns from step 2 as an approval procedure.", I commented, "I am not sure if I know what this means.  There are two step 2s in this document and no table under either"


---
I think once we make these changes, we are ready to test this with a project.  Thoughts?
