### ISSUE TITLE
Create a Guide: Create and/or organize your project's Google Drive

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/knowledgebase-content#74]
### Overview
We need to create a guide to setting up and/or organize your project's Google Drive so it can be easy to navigate.

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Resources/Instructions
- [Guide Document](https://docs.google.com/document/d/1vBcfndEQSU_Edz8h745aMeTNl55_6ZQlEVl90gibcDU/edit)
- Link to the [tool to remake your Header](https://docs.google.com/drawings/d/1YJI1pKheA2uZfI8ICTtR8soJLuhqhoTUrzfv8YQerE4/copy)
#### Draft
- [ ] Ensure you have access to the Google Drive. 
    - [ ] If you do not have access, ask the existing PM to add you to it.
    - [ ] If it does not yet exist, ask Bonnie to create it.
- [ ] Add yourself to the team roster. 
    - [ ] If it does not yet exist, create it using this [template](https://docs.google.com/spreadsheets/d/1DdlWALlH_5HLr7IYFx_ptt3g36Sju-hb1dc34ak0y18/edit?usp=sharing).
- [ ] Organize the drive by numbering the folders and sorting all documents into the relevant folders
    - [ ] 01 Project Overview - New Members Start Here 
    - [ ] 02 Design
    - [ ] 03 Development
    - [ ] 04 Marketing
    - [ ] 05 Forms and Spreadsheets
    - [ ] 06 Meeting Documentation
    - [ ] 07 Working Files
    - [ ] 08 Archive
![image](https://user-images.githubusercontent.com/75456721/104083002-aa3ba000-51ef-11eb-85e6-9c45c31277ff.png)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.

**Comment by fchan218** [comment]
@ag2463 please provide update. if not then we will remove you as assignee
