### ISSUE TITLE
Create Docker documentation for Incubator

### ISSUE THREAD

**Issue by JasonEb** [hackforla/knowledgebase-content#77]
### Overview
We need a guide to building a docker image to deploy software onto Incubator, so that when projects are ready to deploy they know how to make their own docker image.

#### Details
With the Incubator, software and projects are deployed via Docker images. With VRMS, CivicTechJobs, HomeUniteUs, we have a common Django infrastructure and successful docker builds working with Incubator. 

 ### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)

### Resources/Instructions
- [ ] Collect links to Docker files + Docker-compose files for Incubator apps
   - [VRMS repo](https://github.com/hackforla/VRMS)
   - [CivicTechJobs repo](https://github.com/hackforla/CivicTechJobs)
   - [HomeUniteUs repo](https://github.com/hackforla/HomeUniteUs)
- [ ] Investigate Docker do's and don'ts for docker and docker-compose files
- [ ] Create Documentation for best practices on docker and docker-compose files

#### Related Issues
- https://github.com/hackforla/incubator/issues/11 and Introduce a Pre-Deployment Checklist for Incubator
- https://github.com/hackforla/incubator/issues/25
- https://github.com/hackforla/incubator/issues/43

#### tech leads for their respective projects and have deployed on incubator
- Home Unite Us: @tylerthome with 
- VRMS: @spiteless

#### Who is involved
- Incubator
   - Incubator is managed by the DevOps community of practice
      - @sudhara has a list of all project's status on incubator
- Project's deployed on Incubator and their tech leads 
   - Home Unite Us: @tylerthome with 
   - VRMS: @spiteless

#### What to ask for
- [ ] Link to GitHub resources for project that are relevant to docker/incubator
- [ ] Link to google docs, if used
- [ ] Status (complete,making changes, new)
- [ ] Outstanding docker issues, if not listed above under Related Issues
- [ ] Deploy instructions
   -  [ ] How are env variables deployed?
- [ ] How are secrets handled?  Are secrets encrypted?: Not yet answered, but there is an open related issue
   - See also https://github.com/hackforla/knowledgebase-content/issues/67 
- Useful resources for info on deploying to the incubator.  
- [x] URLs for the incubator: https://github.com/hackforla/incubator
- [x] any instructions on how to deploy to incubator, etc.: https://github.com/hackforla/incubator/wiki/Incubator-usage
- [x] Either info on how to get credentials for incubator or how to apply for an account: https://github.com/hackforla/incubator/wiki/Onboarding-Process-for-Project-Team-Leads
- [x] Main contributors / architects for the incubator: see Who is Involved above
- [ ] Review https://github.com/ethanstrominger/hfla-utils/blob/main/docker-compose.yml and related Docker files (dockerfile-node and dockerfile-django)

### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.
