### ISSUE TITLE
Create a Guide: Managing your project's slack channel

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/knowledgebase-content#83]
### Overview
We need to create a guide to managing your slack channel so that you and the volunteers on your project have the best experience possible and that we increase retention.

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)

### Resources
[Guide DRAFT: Managing your project's slack channel](https://docs.google.com/document/d/1-1XZiOajQfY1GRiq9f2CnWv3SsJo3iSseI5iO6tCYb8/edit)

#### Youth Justice Nav
- [ ] Join your project's Slack channel
      - [ ] If you cannot find it, reach out to the PM Community of Practice Lead to confirm.
        - [ ] If confirmed, create the channel by using the +Add channels link in Slack 
      ![image](https://user-images.githubusercontent.com/75456721/104083156-3c907380-51f1-11eb-9977-701fc32a4613.png)
- [ ] Set up meeting reminders in your channel by using the /remind function
      Example of how to use this _/remind #channelname Hi team, a reminder that our team meeting is today at 2:00 pm PST. 
      (Zoom link) Please provide an update in your assigned issue before the meeting. Thank you at 9AM every Saturday._
   -  https://github.com/hackforla/product-management/issues/88
- [ ] Pin important messages onto the topic of the channel so they do not get lost. Some teams pin meeting times and Zoom links.
   - [ ] Make the message that you are going to pin succinct.  After about 2 weeks messages disappear and only the words visible in the pin will remain.

#### Template to use per project
(add other check boxes if you find other ways they are using slack to manage)
```
   - [ ] meeting team link (zoom)
   - [ ] Channel Description
   - [ ] Pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team
```

### Projects to check
- [100 Automations](https://github.com/100automations/website)
   - [x] meeting team link - Looks like the team posts the team meeting link (zoom) manually before the meeting.  
   - [x] Channel Description - The channel description has their domain name in it.
    - [ ] Pins
    - [ ] reminder to update issues 12-24 hours before meeting
   - [x] Signup for the team

- [311 Data](https://github.com/hackforla/311-data)
   - [x] meeting team link (zoom) - in a pin
   - [x] Channel Description (meeting links which are same as hfla website page)
   - [x] Pins (5 pins from 2019 to 2020)
   - [x] reminder to update issues 12-24 hours before meeting 
   - [x] Signup for the team (in a pin)

- [Access the Data](https://github.com/hackforla/access-the-data)
   - [x] meeting team link (zoom)
   - [x] Channel Description
   - [x] Pins
   - [x] reminder to update issues 12-24 hours before meeting 
   - [x] Signup for the team

- [BallotNav](https://github.com/hackforla/ballotnav)
  - [x] meeting team link (zoom)
   - [x] Channel Description
   - [x] Pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [x] Signup for the team

- [Brigade Organizer's Playbook](https://github.com/codeforamerica/brigade-playbook)
   - [ ] meeting team link (zoom)
   - [ ] Channel Description
   - [ ] Pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team

- [Civic Tech Index](https://github.com/civictechindex/CTI-website-frontend)
   - [x] meeting team link (zoom)
   - [x] Channel Description
   - [x] Pins
   - [x] reminder to update issues 12-24 hours before meeting 
   - [x] Signup for the team

- [Civic Tech Jobs](https://github.com/hackforla/CivicTechJobs)
   - [x] meeting team link (zoom) - different links for developers and all team
   - [x] meeting agenda - there is a link in the meeting zoom link reminder that contains the meeting agenda.
   - [x] Channel Description
   - [ ] Pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [x] Signup for the team

- [Civic Tech Structure](https://github.com/hackforla/civic-tech-structure)
   - [ ] meeting team link (zoom)
   - [ ] meeting agenda 
   - [x] Channel Description
   - [ ] Pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team

- [Data Science Projects](https://github.com/hackforla/data-science)
   - [x] meeting team link (zoom) - set manually before meetings
   - [x] Channel Description - in a pin
   - [x] Pins - two pinned messages
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [x] Signup for the team

- [Design Systems](https://github.com/hackforla/design-systems)
   - [x] meeting team link (zoom)
   - [x] meeting Agenda
   - [x] Channel Description
   - [ ] Pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team

- [Engage](https://github.com/hackla-engage)
   - [x] meeting team link (zoom)
   - [x] Channel Description - link to a google doc
   - [x] Pins - more than 10 pinned messages
   - [x] reminder to update issues 12-24 hours before meeting - manually done when 
          necessary
   - [ ] Signup for the team

- [Expunge-Assist (formerly known as Record Clearance)](https://github.com/hackforla/expunge-assist)
   - [x] meeting team link (zoom)
   - [x] Channel Description
   - [x] Pins - about 10 pins since 2019
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [x] Signup for the team- explained when necessary
   - [x] VRMS slack integration module

- [Food Oasis](https://github.com/hackforla/food-oasis)
   - [ ] meeting team link (zoom)
   - [x] Channel Description
   - [x] Pins - 5 pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team

- [GreenEarthOS](https://github.com/hackforla/climate-project)
- - [x] meeting team link (zoom)
   - [ ] Channel Description
   - [ ] Pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team

- [Guides](https://github.com/hackforla/guides) 
- - [x] meeting team link (zoom)
   - [ ] Channel Description
   - [x] Pins - 1 pinned message
   - [x] reminder to update issues 12-24 hours before meeting  - reminders are set during or 
           immediately after meetings
   - [ ] Signup for the team

- [HomeUniteUs](https://github.com/hackforla/homeuniteus)
- - [x] meeting team link (zoom) - in topic
   - [x] Channel Description
   - [x] Pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team

- [Internship project](https://github.com/hackforla/internship)
- - [x] meeting team link (zoom)
   - [x] Channel Description
   - [x] Pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team

- [Lucky Parking](https://github.com/hackforla/lucky-parking)
   - [x] meeting team link (zoom) - posted manually before the meeting
   - [x] Channel Description
   - [x] Pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team

- [Open Community Survey](https://github.com/hackforla/open-community-survey)
- - [x] meeting team link (zoom) - in channel description
   - [x] Channel Description
   - [ ] Pins
   - [x] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team

- [TDM Calculator](https://github.com/hackforla/tdm-calculator)
   - [x] meeting team link (zoom) - in a pin
   - [x] Channel Description
   - [x] Pins - 15 pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team

- [VRMS](https://github.com/hackforla/vrms)
   - [x] meeting team link (zoom) - in a pin
   - [x] Channel Description
   - [x] Pins - 2 pins
   - [x] reminder to update issues 12-24 hours before meeting - mentioned in the meeting 
          reminder
   - [ ] Signup for the team
   
- [Hack for LA's Website](https://github.com/hackforla/website)
   - [x] meeting team link (zoom) - in a pin
   - [x] meeting agenda - in a pin
   - [x] Channel Description
   - [x] Pins - 4 pins
   - [ ] reminder to update issues 12-24 hours before meeting 
   - [ ] Signup for the team
   
- [Youth Justice Nav](https://github.com/hackforla/YouthJusticeNav/)
   - [x] meeting team link (zoom) - in a pin
   - [x] Channel Description
   - [x] reminder to update issues 12-24 hours before meeting - added to the slackbot zoom 
          meeting reminder
   - [ ] Signup for the team
### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.
